# -*- coding: utf-8 -*-
"""Deep_Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14USilXJgNivYlRvpZExdGU9j08FgE0se
"""

import random
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

SEED=42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

X,y = fetch_california_housing(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=SEED)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(128, activation="relu"),
    layers.Dropout(0.2),
    layers.Dense(64, activation="relu"),
    layers.Dropout(0.2),
    layers.Dense(1)
])
model.summary()

model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss="mse",
    metrics=["mae"]
)

early_stopping = keras.callbacks.EarlyStopping(
    monitor="val_loss", patience=8, restore_best_weights=True
)

history = model.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=100,
    batch_size=64,
    verbose=2,
    callbacks=[early_stopping]
)

from sklearn.metrics import mean_absolute_error, r2_score
y_pred = model.predict(X_test).flatten()
print(f"Test MAE: {mean_absolute_error(y_test, y_pred):.3f}")
print(f"Test R²:  {r2_score(y_test, y_pred):.3f}")

from sklearn.ensemble import HistGradientBoostingRegressor

gb = HistGradientBoostingRegressor(random_state=42)
gb.fit(X_train, y_train)
y_pred_gb = gb.predict(X_test)
print(f"GB Test MAE: {mean_absolute_error(y_test, y_pred_gb):.3f}")
print(f"GB Test R²:  {r2_score(y_test, y_pred_gb):.3f}")

import matplotlib.pyplot as plt
plt.scatter(y_test, y_pred, alpha=0.3, s=8)
plt.plot([0, 5], [0, 5], "r--")
plt.xlabel("Gerçek"); plt.ylabel("Tahmin")
plt.show()