# -*- coding: utf-8 -*-
"""22 Eylül .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MbqGFx4XjwrdcOUHOvTywoUcq4K6bJMV
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
import statsmodels.api as sm

sns.set_style("whitegrid")
sns.set_context("poster")
import warnings
warnings.filterwarnings("ignore")
#

column_names = [
    "Sex",             # Kategorik: M, F, I
    "Length",          # Sayısal (float)
    "Diameter",        # Sayısal (float)
    "Height",          # Sayısal (float)
    "Whole_weight",    # Sayısal (float)
    "Shucked_weight",  # Sayısal (float)
    "Viscera_weight",  # Sayısal (float)
    "Shell_weight",    # Sayısal (float)
    "Rings"            # Hedef değişken (int) - tahmin edeceğimiz değer
]
df= pd.read_csv("abalone.data",header=None,names=column_names)
df["Age"] = df["Rings"]+1.5
df.head(2)

print("Veri Seti Boyutu:",df.shape)
df.info()

df.describe().T

df["Sex"].value_counts()

plt.figure(figsize=(8,6))
sns.histplot(df["Rings"],bins=30,kde= True, color ="steelblue")

plt.title("Ring Sayıları")
plt.xlabel("Ring Sayısı")
plt.ylabel("Frekans")

plt.show()

numeric_cols = df.select_dtypes(include=[np.number]) # numeric_cols = df.drop(columns=["X"])
corr_matrix = numeric_cols.corr()
plt.figure(figsize=(12, 10
                    ))
sns.heatmap(corr_matrix, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Korelasyon Matrisi")
plt.show()

df_encoded = pd.get_dummies(df, columns=["Sex"],drop_first=True)
df_encoded["Sex_I"] =df_encoded["Sex_I"].astype(int)
df_encoded["Sex_M"] =df_encoded["Sex_M"].astype(int)

df_encoded

X= df_encoded.drop(columns=["Rings","Age"])
y= df_encoded["Rings"]

X_train,X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

model=LinearRegression()
model.fit(X_train,y_train)
model_pred =model.predict(X_test)

r2_multi = r2_score(y_test,model_pred)
print("R2 Değeri:",r2_multi)
mae_multi = mean_absolute_error(y_test,model_pred)
print("MAE Değeri:",mae_multi)
mse_multi = mean_squared_error(y_test,model_pred)
print("MSE Değeri:",mse_multi)

X_train_sm = sm.add_constant(X_train)
model_sm = sm.OLS(y_train,X_train_sm).fit()
model_sm.summary()

plt.figure(figsize=(7,7))
plt.scatter(y_test,model_pred ,alpha=0.4,color="teal")
plt.plot(y_test,y_test,"r")
plt.xlabel("Gerçek Değerler")
plt.ylabel("Tahmin Edilen Değerler")

residual =y_test-model_pred
fig, axes = plt.subplots(1,2,figsize=(12,6))
axes[0].scatter(model_pred,residual,alpha=0.4,color="darkorange")
axes[0].axhline(y=0,color="red",linestyle="--")
axes[0].set_xlabel("Gerçek Değerler")
axes[0].set_ylabel("Hata Değeri")
axes[0].set_title("Artık Grafiği")
sns.histplot(y_test,kde=True,ax=axes[1],color="slateblue")
axes[1].set_title("Gerçek Değerler")
axes[1].set_title("Normallik Kontrolü")
axes[1].set_xlabel("Hata Değeri")
axes[1].set_ylabel("Frekans")

plt.tight_layout()
plt.show()

from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline

degress =[1,2,3,4]

poly_results= {}

plt.figure(figsize=(12,6))
X_one_train =X_train[['Shell_weight']]
X_one_test =X_test[['Shell_weight']]
sort_idx =X_one_test['Shell_weight'].values.argsort()
x_sorted =X_one_test['Shell_weight'].values[sort_idx]
plt.scatter(X_one_test['Shell_weight'],y_test,alpha=0.4,color="#1f77b4",label="Gerçek Değerler")
for degree in degress:
    model_poly = make_pipeline(PolynomialFeatures(degree),LinearRegression())
    model_poly.fit(X_one_train,y_train)
    poly_pred = model_poly.predict(X_one_test)
    poly_results[degree]={
        "r2": r2_score(y_test,poly_pred),
        "Rmse" : np.sqrt(mean_squared_error(y_test,poly_pred))
}
    y_line = model_poly.predict(x_sorted.reshape(-1,1))
    plt.plot(x_sorted,y_line,linewidth=2,label=f"Derece: {degree}")
plt.xlabel("Shell Weight")
plt.ylabel("Rings")
plt.legend()
plt.show()

pd.DataFrame(poly_results).T.rename_axis("Derece")

poly_features = PolynomialFeatures(degree=2)
X_poly_train = poly_features.fit_transform(X_train)
X_poly_test = poly_features.transform(X_test)

poly_multi_model =LinearRegression()
poly_multi_model.fit(X_poly_train,y_train)
poly_multi_pred =poly_multi_model.predict(X_poly_test)

r2_score_poly = r2_score(y_test,poly_multi_pred)
print("R2 Değeri:",r2_score_poly)
mae_poly = mean_absolute_error(y_test,poly_multi_pred)
print("MAE Değeri:",mae_poly)
rmse_poly = np.sqrt(mean_squared_error(y_test,poly_multi_pred))
print("RMSE Değeri:",rmse_poly)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (confusion_matrix,ConfusionMatrixDisplay,accuracy_score,precision_score,
recall_score,f1_score,classification_report,roc_curve,roc_auc_score)

column_names = [
    "Checking_account_status",   # A11-A14: mevcut vadesiz hesap durumu
    "Duration_months",           # sayısal: kredi vadesi (ay)
    "Credit_history",            # A30-A34: geçmiş kredi ödeme durumu
    "Purpose",                   # A40-A410: kredinin amacı
    "Credit_amount",             # sayısal: kredi tutarı
    "Savings_account",           # A61-A65: tasarruf hesabı durumu
    "Employment_since",          # A71-A75: mevcut işte çalışma süresi
    "Installment_rate",          # sayısal: taksit oranı (gelire göre %)
    "Personal_status_sex",       # A91-A95: medeni durum ve cinsiyet
    "Other_debtors",             # A101-A103: diğer borçlular/kefiller
    "Present_residence_since",   # sayısal: mevcut ikametgahta kaç yıldır oturuyor
    "Property",                  # A121-A124: sahip olunan mülk türü
    "Age",                       # sayısal: yaş
    "Other_installment_plans",   # A141-A143: diğer taksitli ödeme planları
    "Housing",                   # A151-A153: konut durumu (kira/kendi/bedava)
    "Existing_credits",          # sayısal: bu bankadaki mevcut kredi sayısı
    "Job",                       # A171-A174: meslek/iş durumu
    "People_liable",             # sayısal: bakmakla yükümlü olunan kişi sayısı
    "Telephone",                 # A191-A192: telefon sahipliği
    "Foreign_worker",            # A201-A202: yabancı işçi mi
    "Target"                     # 1 = İyi (Good), 2 = Kötü (Bad) kredi riski
]
df = pd.read_csv("german.data", sep=r"\s+", header=None, names=column_names)

df.head(2)

print("Veri seti boyutu:",df.shape)
df.info()

df.describe().T

df["Bad_risk"] = (df["Target"]==2).astype(int)
df =df.drop(columns=["Target"])
df["Bad_risk"].value_counts(normalize=True).rename(index={0:"iyi",1:"Kötü"})

plt.figure(figsize=(8,6))
sns.countplot(x="Bad_risk",data=df,palette="pastel")

plt.title("Kredi Miktarı")
plt.xlabel("Kredi Miktarı")
plt

numeric_cols=df.select_dtypes(include=[np.number])
corr_matrix = numeric_cols.corr()
plt.figure(figsize=(12,8))
sns.heatmap(corr_matrix,annot=True,cmap="coolwarm",fmt=".2f")

categorical_cols = df.select_dtypes(include="object").columns.tolist()
df_encoded = pd.get_dummies(df,columns=categorical_cols,drop_first=True)
bool_cols = df_encoded.select_dtypes(include="bool").columns.tolist()
df_encoded[bool_cols] = df_encoded[bool_cols].astype(int)
df_encoded.head()

X=df_encoded.drop(columns=["Bad_risk"])
y=df_encoded["Bad_risk"]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

scaler  = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled=pd.DataFrame(X_train_scaled,columns=X_train.columns,index=X_train.index)
X_test_scaled=pd.DataFrame(X_test_scaled,columns=X_test.columns,index=X_test.index)
X_train_scaled.head()

log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train_scaled,y_train)

y_proba =log_reg.predict_proba(X_test_scaled)[:,1]
y_pred =log_reg.predict(X_test_scaled)

results_preview =pd.DataFrame({
    "Gerçek:": y_test.values[:10],
    "Tahmin:": y_pred[:10],
    "Olasılık:": y_proba[:10].round(2)
})

results_preview

cm = confusion_matrix(y_test,y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=["iyi (0)", "Kötü (1)"])
disp.plot(cmap=plt.cm.Blues)
plt.title("Confusion Matrix")
plt.show()
#

accuracy = accuracy_score(y_test,y_pred)
precision = precision_score(y_test,y_pred)
recall = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)

print("Accuracy:",accuracy)
print("Precision:",precision)
print("Recall:",recall)
print("F1 Score:",f1)


print(classification_report(y_test,y_pred))

from sklearn.svm import SVC
from sklearn.decomposition import PCA

svm_linear = SVC(kernel="linear",C=1.0,probability=True ,random_state=42)
svm_linear.fit(X_train_scaled,y_train)

y_pred_linear = svm_linear.predict(X_test_scaled)
y_proba_linear = svm_linear.predict_proba(X_test_scaled)[:,1]

print(f"toplam destek vektörü sayısı: {svm_linear.n_support_.sum()}")
print(f"support_vectors_: {svm_linear.support_vectors_.shape}")

acc_svm = accuracy_score(y_test,y_pred_linear)
prec_svm = precision_score(y_test,y_pred_linear)
rec_svm = recall_score(y_test,y_pred_linear)
f1_svm = f1_score(y_test,y_pred_linear)

print("Accuracy:",acc_svm)
print("Precision:",prec_svm)
print("Recall:",rec_svm)
print("F1 Score:",f1_svm)
print(classification_report(y_test,y_pred_linear))

svm_rbf = SVC(kernel="rbf",C=1.0,gamma="scale",probability=True,random_state=42)
svm_rbf.fit(X_train_scaled,y_train)

y_pred_rbf=svm_rbf.predict(X_test_scaled)
y_proba_rbf=svm_rbf.predict_proba(X_test_scaled)[:,1]

acc_svm_rbf = accuracy_score(y_test,y_pred_rbf)
prec_svm_rbf = precision_score(y_test,y_pred_rbf)
rec_svm_rbf = recall_score(y_test,y_pred_rbf)
f1_svm_rbf = f1_score(y_test,y_pred_rbf)
auc = roc_auc_score(y_test,y_proba_rbf)

print("Accuracy:",acc_svm_rbf)
print("Precision:",prec_svm_rbf)
print("Recall:",rec_svm_rbf)
print("F1 Score:",f1_svm_rbf)
print("AUC:",auc)

from sklearn.model_selection import GridSearchCV,cross_val_score

param_grid = {
    "C":[0.1,1,10,100],
    "gamma":[1,0.1,0.01,0.001],
    "kernel":["rbf"]
}

grid_search = GridSearchCV(SVC(probability=True),param_grid,cv=5,scoring="f1",n_jobs=-1)
grid_search.fit(X_train_scaled,y_train)
print("En iyi parametreler:",grid_search.best_params_)
print("En iyi skor:",grid_search.best_score_)

svm_best = grid_search.best_estimator_

y_pred_best = svm_best.predict(X_test_scaled)
y_proba_best = svm_best.predict_proba(X_test_scaled)[:,1]


acc_svm_best = accuracy_score(y_test,y_pred_best)
prec_svm_best = precision_score(y_test,y_pred_best)
rec_svm_best = recall_score(y_test,y_pred_best)
f1_svm_best = f1_score(y_test,y_pred_best)
auc_svm_best = roc_auc_score(y_test,y_proba_best)


print("Accuracy:",acc_svm_best)
print("Precision:",prec_svm_best)
print("Recall:",rec_svm_best)
print("F1 Score:",f1_svm_best)
print("AUC:",auc_svm_best)

from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import PCA
pca = PCA(n_components=3,random_state=42)
X_train_pca = pca.fit_transform(X_train_scaled)
np.random.seed(42)
sample_idx =np.random.choice(len(X_train_pca))
sample_point =X_train_pca[sample_idx]

distances = np.sqrt(((X_train_pca-sample_point)**2).sum(axis=1))
k_example=10
nearest_neighbors = distances.argsort()[1:k_example+1]
knn = KNeighborsClassifier(n_neighbors=k_example)
knn.fit(X_train_scaled,y_train)

plt.figure(figsize=(8,6))
plt.scatter(X_train_pca[:,0],X_train_pca[:,1],c=y_train,cmap=plt.cm.Paired,alpha=0.70,s=20)
plt.scatter(sample_point[0],sample_point[1],c="red",marker="x",s=400,label="Örnek Nokta")

plt.xlabel("Öznitelik 1")
plt.ylabel("Öznitelik 2")
plt.legend()
plt.show()

k_values = list(range(1,21,2))
cv_f1_scores=[]
cv_accuracy_scores=[]
for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    f1_scores = cross_val_score(knn,X_train_scaled,y_train,cv=5,scoring="f1")
    accuracy_scores = cross_val_score(knn,X_train_scaled,y_train,cv=5,scoring="accuracy")
    cv_f1_scores.append(np.mean(f1_scores))
    cv_accuracy_scores.append(np.mean(accuracy_scores))
plt.figure(figsize=(12,8))
plt.plot(k_values,cv_f1_scores,marker="o",label="Ortalama f1 skoru")
plt.plot(k_values,cv_accuracy_scores,marker="s",label="Ortalama doğruluk skoru")
plt.xlabel("K Değeri")
plt.ylabel("Skoru")
plt.legend()
plt.xticks(k_values)
plt.show()

param_grid = {
    "n_neighbors":list(range(1,21,2)),
    "weights":["uniform","distance"],
    "p":[1,2]
}

grid_search = GridSearchCV(KNeighborsClassifier(),param_grid,cv=5,scoring="f1",n_jobs=-1)
grid_search.fit(X_train_scaled,y_train)
print("En iyi parametreler:",grid_search.best_params_)
print("En iyi skor:",grid_search.best_score_)

knn_best =grid_search.best_estimator_
y_pred_knn = knn_best.predict(X_test_scaled)
y_proba_knn = knn_best.predict_proba(X_test_scaled)[:,1]

acc_knn = accuracy_score(y_test,y_pred_knn)
prec_knn = precision_score(y_test,y_pred_knn)
rec_knn = recall_score(y_test,y_pred_knn)
f1_knn = f1_score(y_test,y_pred_knn)
auc_knn = roc_auc_score(y_test,y_proba_knn)

print("Accuracy:",acc_knn)
print("Precision:",prec_knn)
print("Recall:",rec_knn)
print("F1 Score:",f1_knn)
print("AUC:",auc_knn)
#

cm = confusion_matrix(y_test,y_pred_knn)
fig,ax =plt.subplots(figsize=(8,6))
disp = ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=["iyi (0)","kötü (1)"])
disp.plot(ax=ax,cmap=plt.cm.Blues)
plt.title("Confusion Matrix")
plt.show()
#

# Karşılaştırma için lojistik regresyon ve SVM modellerini de aynı veriyle eğitelim
log_reg = LogisticRegression(max_iter=1000, random_state=42)
log_reg.fit(X_train_scaled, y_train)
y_pred_log = log_reg.predict(X_test_scaled)
y_proba_log = log_reg.predict_proba(X_test_scaled)[:, 1]

svm_rbf = SVC(kernel="rbf", C=1.0, gamma="scale", probability=True, random_state=42)
svm_rbf.fit(X_train_scaled, y_train)
y_pred_svm = svm_rbf.predict(X_test_scaled)
y_proba_svm = svm_rbf.predict_proba(X_test_scaled)[:, 1]

# Tüm modellerin metriklerini tek bir tabloda topla
comparison_df = pd.DataFrame({
    "Model": ["Lojistik Regresyon", "SVM (RBF)", f"KNN (k={grid_search.best_params_['n_neighbors']})"],
    "Doğruluk": [
        accuracy_score(y_test, y_pred_log), accuracy_score(y_test, y_pred_svm), acc_knn
    ],
    "Kesinlik": [
        precision_score(y_test, y_pred_log), precision_score(y_test, y_pred_svm), prec_knn
    ],
    "Duyarlılık": [
        recall_score(y_test, y_pred_log), recall_score(y_test, y_pred_svm), rec_knn
    ],
    "F1": [
        f1_score(y_test, y_pred_log), f1_score(y_test, y_pred_svm), f1_knn
    ],
    "AUC": [
        roc_auc_score(y_test, y_proba_log), roc_auc_score(y_test, y_proba_svm), auc_knn
    ]
})

comparison_df.round(3)