# -*- coding: utf-8 -*-
"""Kaggle_Example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12PyhFMf-32qFVDT5aPHorWH7FVYGSUsO
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("yogeshm01/spotify-artist-streaming-analytics-20152025")

print("Path to dataset files:", path)

import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats
import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.stats.outliers_influence import variance_inflation_factor as VIF
from statsmodels.stats.multicomp import pairwise_tukeyhsd

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

df = pd.read_csv("/content/spotify_data_processed.csv")
df.head(5)

df.info()

df.sample(10,random_state=1)

df_sorted = df.sort_values('log_stream_count' ,ascending=False)
df_sorted.head()

df.shape

ozet= pd.DataFrame({
    "dtype":df.dtypes,
    "eksik_deger":df.isnull().sum(),
    "unique_deger":df.nunique(),
    "eksik_deger_yuzdesi":(df.isnull().mean()*100).round(2),
})

print(ozet)

df.isnull().sum()

df.duplicated().sum()

df.describe()

sayisal_sutunlar = df.select_dtypes(include=[np.number]).columns.tolist()
sozel_sutunlar = df.select_dtypes(exclude=[np.number]).columns.tolist()
sayisal_sutunlar
#id değerlerinin benzersiz olması bir işimize yaramaz kaldıralım kolonu
#sayisal_sutunlar.remove("track_id")

for col in sayisal_sutunlar:
  print(f"skew: {df[col].skew():.2f} kurt: {df[col].kurt():.2f}")

fig,axes = plt.subplots(2,3,figsize=(15,6))
for ax ,col in zip(axes.flatten(),sayisal_sutunlar):
  sns.histplot(df[col], ax=ax, kde=True,bins =30)
  ax.set_title(col)
plt.tight_layout
plt.savefig("histogramlar.png",dpi = 300)
plt.show ()

fig,axes = plt.subplots(2,3,figsize=(15,6))
for ax ,col in zip(axes.flatten(),sayisal_sutunlar):
  sns.boxplot(y=df[col], ax=ax)
  ax.set_title(col)
plt.tight_layout
plt.savefig("boxplot.png",dpi = 300)
plt.show ()

for col in sozel_sutunlar:

  print((df[col].value_counts(dropna=False, normalize=True)*100).round(2))

korelasyon = df[sayisal_sutunlar].corr(numeric_only=True)
print("------ Korelasyon Matrisi-----")
print(korelasyon.round(2))

plt.figure(figsize=(16, 12))

mask = np.triu(np.ones_like(korelasyon, dtype=bool))

sns.heatmap(
    korelasyon,
    mask=mask,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    center=0,
    square=True,
    linewidths=0.5,
    cbar_kws={"shrink": 0.8},
    annot_kws={"size": 8}
)

plt.title("Korelasyon Matrisi", fontsize=14, pad=20)
plt.xticks(rotation=45, ha="right", fontsize=9)
plt.yticks(rotation=0, fontsize=9)
plt.tight_layout()
plt.savefig("korelasyon_matrisi.png", dpi=200, bbox_inches="tight")
plt.show()

"""korelasyon verileri bize anlamlı bir bilgi vermedi. aralarında korelasyon olan veriler hali hazırda birbiri ile direkt olarak ilişkili. Dakika ve milisaniye gibi veriler zaten birbiri içinde korelasyon içerisindeler. Bu kolonların bazılarını kaldırmak ya da verilerde anlamlı bir çıkarım içerisinde olmadıklarını anlamamız gerekiyor."""

# Bu adımdan itibaren istatistiksel olarak verimizi yorumlayacağız.

def ortalama_guven_aralığı(seri,guven=0.95):
  veri = seri.dropna()
  n = len(veri)
  ortalama = veri.mean()
  sem = stats.sem(veri) # standart error of the mean
  t_kritik = stats.t.ppf((1+guven)/2 ,df =n-1)
  hata_payi = t_kritik*sem
  return ortalama,ortalama-hata_payi,ortalama+hata_payi

print(f"{'değişken':20s},{'Ortalama':>12s},{'%95 Alt':>12s},{'%95 Üst':>12s}")
for degisken in sayisal_sutunlar:
  ortalama,alt,ust = ortalama_guven_aralığı(df[degisken])
  print(f"{degisken:20s},{ortalama:>12.2f},{alt:>12.2f},{ust:>12.2f}")

print(f"{'Değişken':20s} {'Shapiro-Wilk p':>16s} {'DAgostino p'} Yorum ")
for col in sayisal_sutunlar:
  veri= df[col].dropna()
  # shapiro n> 5000 den fazla olursa güvenilmez olur
  ornek = veri.sample(min(len(veri),5000),random_state=0)
  sw_stat, sw_p = stats.shapiro(ornek)
  da_stat, da_p = stats.normaltest(veri)
  yorum = "Normal dağılım varsayımı sağlanmaktadır." if sw_p > 0.05 else "Normal dağılım varsayımı sağlanmamaktadır."
  print(f"{col:20s} {sw_p:>16.4f} {da_p:>16.4f} {yorum}")

fig, axes = plt.subplots(1, len(sayisal_sutunlar), figsize=(24, 8))
for ax, col in zip(axes, sayisal_sutunlar):
    stats.probplot(df[col].dropna(), dist="norm", plot=ax)
    ax.set_title(f"Q-Q Grafiği: {col}")
plt.tight_layout()
plt.show()

grup0 = df.loc[df["explicit"] == 0, "stream_count"].dropna()
grup1 = df.loc[df["explicit"] == 1, "stream_count"].dropna()

levene_stat, levene_p = stats.levene(grup0, grup1)
print("Varsayımlar homojendir." if levene_p > 0.05 else "Varsayımlar homojen değildir.")
__, p0=stats.shapiro(grup0.sample(min(len(grup0),5000),random_state=0))
__, p1=stats.shapiro(grup1.sample(min(len(grup1),5000),random_state=0))
normal_mi = (p0>0.05) and (p1>0.05)
print(f"grup normallik p değerleri: churn=0 -> {p0:.4f},churn=1 -> {p1:.4f}")

gruplar= [g["danceability"].dropna().values for _,g in df.groupby("country")]

f_stat, anova_p = stats.f_oneway(*gruplar)
h_stat, kw_p= stats.kruskal(*gruplar)

print(f" tek yönlü anova: f={f_stat:.3f},p={anova_p:.4f}")
print(f"kruskal-wallis: h={h_stat:.3f},p={kw_p:.4f}")

genel_ortalama = df["danceability"].mean()
ss_between = sum(len(g)*(g.mean()-genel_ortalama)**2 for g in gruplar)
ss_total = sum((df["danceability"].dropna()-genel_ortalama)**2)
eta_kare = ss_between/ss_total
print(f"Eta Kare: {eta_kare:.4f} (0.01 küçük,0.06 orta, 0.14 büyük etki)")

tukey = pairwise_tukeyhsd(
    endog=df["danceability"].dropna(),
    groups=df.loc[df["danceability"].notna(), "country"],
    alpha=0.05
)

print(tukey)

def cramers_v(x,y):
  tablo =pd.crosstab(x,y)
  chi2 = stats.chi2_contingency(tablo)[0]
  n =tablo.sum().sum()
  k= min(tablo.shape)-1
  return np.sqrt(chi2/(n*k))

capraz = pd.crosstab(df["stream_count"],df["popularity_category"])
chi2,p,dof,beklenen =stats.chi2_contingency(capraz)
v= cramers_v(df["stream_count"],df["popularity_category"])
print(f"chi2={chi2:.4f},p={p:.4f},v={v:.4f}")
print(f"Cramer's V: {v:.4f}")
print("\n Çapraz Tablo")
print(capraz)

def  korelasyon_p_matrisi(veri,yontem ="pearson"):
  sutunlar = veri.columns
  kat = pd.DataFrame(np.ones((len(sutunlar),len(sutunlar))),index=sutunlar,columns=sutunlar)
  pval = pd.DataFrame(np.zeros((len(sutunlar),len(sutunlar))),index=sutunlar,columns=sutunlar)
  for i in sutunlar:
    for j in sutunlar:
      if i == j:
        kat.loc[i,j] = 1.0
        pval.loc[i,j] = 0.0
        continue
      ortak = veri[[i,j]].dropna()
      x_seri,y_seri = ortak.iloc[:,0],ortak.iloc[:,1]
      if yontem == "pearson":
        r,p = stats.pearsonr(x_seri,y_seri)
      else:
        r,p = stats.spearmanr(x_seri,y_seri)
      kat.loc[i,j] = float(r)
      pval.loc[i,j] = float(p)
  return kat,pval

pearson_r, pearson_p = korelasyon_p_matrisi(df[sayisal_sutunlar],"pearson")
print("--- pearson korelasyon katsayıları ---")
print(pearson_r)
print("\n--- pearson p değerleri ---")
print(pearson_p.round(4))

fig , axes = plt.subplots(1,2, figsize=(16,6))
sns.heatmap(pearson_r,annot=True,fmt=".2f",cmap="coolwarm",center=0,vmin=-1,vmax=1,ax=axes[0])
axes[0].set_title("Pearson Korelasyon Matrisi")

anlamli_maske = pearson_p > 0.05

sns.heatmap(pearson_p,annot=True,fmt=".2f",cmap="coolwarm",center=0,vmin=-1,vmax=1,mask=~anlamli_maske,ax=axes[1],cbar=False)
axes[1].set_title("Anlamli Korelasyonlar")
plt.tight_layout()
plt.show()

X_vif = df[["energy", "danceability", "upbeat_score", "loudness", "tempo"]].dropna()
X_vif = sm.add_constant(X_vif)
vif_tablosu = pd.DataFrame({
    "Değişken":X_vif.columns,
    "VIF":[VIF(X_vif.values, i) for i in range(X_vif.shape[1])]
})
print(vif_tablosu)   # 1 yerine 0 dan başlattık

X_vif = df[["energy", "danceability", "upbeat_score", "loudness", "tempo"]].dropna()
X_vif_const = sm.add_constant(X_vif)

vif_tablosu = pd.DataFrame({
    "Değişken": X_vif.columns,
    "VIF": [VIF(X_vif_const.values, i) for i in range(1, X_vif_const.shape[1])]
})
print(vif_tablosu) # 0 index sabit değer çokta önemli değil onu yoksalım

X_vif = df[["energy", "danceability", "upbeat_score", "loudness", "tempo"]].dropna()
X_vif = sm.add_constant(X_vif)

vif_tablosu = pd.DataFrame({
    "Değişken": [X_vif.columns[i]for i in range(1, X_vif.shape[1])],
    "VIF": [VIF(X_vif.values, i) for i in range(1, X_vif.shape[1])]
})
print(vif_tablosu)

model_verisi = df[["log_stream_count", "popularity"]].dropna()

model = smf.ols(formula="log_stream_count ~ popularity", data=model_verisi)
sonuc = model.fit()
print(sonuc.summary())

model_verisi = df[["popularity", "danceability", "energy", "loudness", "tempo"]].dropna()

model = smf.ols(formula="popularity ~ danceability + energy + loudness + tempo", data=model_verisi)
sonuc = model.fit()
print(sonuc.summary())

pca_verisi = df[sayisal_sutunlar].dropna()
scaler = StandardScaler()
X_scaled = scaler.fit_transform(pca_verisi)
pca = PCA()
X_pca = pca.fit_transform(X_scaled)
acıklanan_varyans = pca.explained_variance_ratio_
print(acıklanan_varyans)