# -*- coding: utf-8 -*-
"""Untitled166.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L_X7QBVy4fiTwSoQf0_hMozy8XAYBl4V
"""

import random
import platform
import sys
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

warnings.filterwarnings("ignore")

SEED=42
random.seed(SEED)
np.random.seed(SEED)

sns.set_theme(style="whitegrid",context ="notebook")
plt.rcParams["figure.figsize"]=(7,4)
plt.rcParams["figure.dpi"] = 110


print(f"python: {sys.version.split()[0]}")
print(f"Platform:{platform.platform()}")
print(f"seaborn: {sns.__version__}")
print(f"pandas: {pd.__version__}")
print(f"numpy: {np.__version__}")
print(f"sklearn: {sklearn.__version__}")

from sklearn.datasets import load_diabetes, load_breast_cancer

diab=load_diabetes(as_frame=True)
diab.frame.head(2)

diab.frame.info()

X_reg =diab.data
y_reg=diab.target

X_reg= diab.frame.drop("target",axis=1)
y_reg=diab.frame["target"]

y_reg

fig, axes = plt.subplots(1,2, figsize=(12,4))

sns.histplot(y_reg,kde=True,ax=axes[0],color="steelblue")
axes[0].set_title("Diabet hedef değişken dağılımı")
axes[0].set_xlabel("Hastalık ilerleme skoru")

corr =pd.concat([X_reg,y_reg.rename("hedef")],axis =1).corr()
sns.heatmap(corr,annot=True,fmt=".1f",cmap="coolwarm",center=0,
            axes=axes[1],cbar=False, annot_kws ={"size":7})
axes[1].set_title("Diabet veri setindeki değişkenler arasındaki korelasyon")

plt.tight_layout()
plt.show()

from sklearn.model_selection import train_test_split
Xr_train,Xr_test,yr_train,yr_test=train_test_split(X_reg,y_reg,test_size=0.2,random_state=SEED)

print(f"{Xr_train.shape[0]}")
Xr_test.shape[0]

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from sklearn.dummy import DummyRegressor
baseline = DummyRegressor(strategy="mean").fit(Xr_train,yr_train)

linear = LinearRegression().fit(Xr_train,yr_train)

def regresyon_raporu (model,X, y,ad):
  tahmin=model.predict(X)
  return{
     "Model" :ad,
     "Mae"   : mean_absolute_error(y,tahmin),
     "mse"   : mean_squared_error(y,tahmin),
     "rmse"  : np.sqrt(mean_squared_error(y,tahmin)),
     "r2"    : r2_score(y,tahmin)
    }
sonuc = pd.DataFrame([
    regresyon_raporu(baseline,Xr_train,yr_train,"Baseline"),
    regresyon_raporu(linear,Xr_test,yr_test,"Linear")
]).set_index("Model").round(3)
sonuc

katsayilar = pd.Series(linear.coef_, index=X_reg.columns).sort_values()

plt.figure(figsize=(7, 4))
katsayilar.plot(kind="barh", color=np.where(katsayilar > 0, "tab:blue", "tab:red"))
plt.title("Doğrusal regresyon katsayıları")
plt.xlabel("Katsayı değeri")
plt.tight_layout()
plt.show()


tahmin = linear.predict(Xr_test)
plt.figure(figsize=(5, 5))
plt.scatter(yr_test, tahmin, alpha=0.7)
lim = [yr_test.min(), yr_test.max()]
plt.plot(lim, lim, "r--", label="Mükemmel tahmin")
plt.xlabel("Gerçek değer")
plt.ylabel("Tahmin")
plt.title("Gerçek vs. Tahmin (test kümesi)")
plt.legend()
plt.tight_layout()
plt.show()

from sklearn.linear_model import Ridge,Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

modeller= {
    "Doğrusal": make_pipeline(StandardScaler(),LinearRegression()),
    "Ridge": make_pipeline(StandardScaler(),Ridge(alpha=1.0)),
    "Lasso": make_pipeline(StandardScaler(),Lasso(alpha=1.0))
}

satirlar =[]

for ad,m in modeller.items():
  m.fit(Xr_train,yr_train)
  satirlar.append(regresyon_raporu(m,Xr_test,yr_test,ad))

pd.DataFrame(satirlar).set_index("Model").round(3)

lasso= modeller["Lasso"].named_steps["lasso"]
pd.Series(lasso.coef_,index=X_reg.columns).round(2).to_frame("Lasso değişkenler").T

print(modeller.keys())

bc = load_breast_cancer(as_frame=True)
X_clf, y_clf = bc.data, bc.target
X_clf.head(2)

print("Sınıf dağılımı(0=habis, 1= iyi huylu):")
print(y_clf.value_counts().rename({0:"habis",1:"iyi"}))
X_clf.iloc[:,:6].describe().T.round(2)

Xc_train,Xc_test,yc_train,yc_test=train_test_split(X_clf,y_clf,test_size=0.2,random_state=SEED)

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score

siniflandiricilar = {
    "Baseline": DummyClassifier(strategy="most_frequent").fit(Xc_train,yc_train),
    "Logistic": LogisticRegression().fit(Xc_train,yc_train),
    "KNN": KNeighborsClassifier().fit(Xc_train,yc_train),
    "Karar ağacı": DecisionTreeClassifier().fit(Xc_train,yc_train),
    "Rastgele orman": RandomForestClassifier().fit(Xc_train,yc_train)
}


satirlar =[]

for ad,m in siniflandiricilar.items():
  m.fit(Xc_train,yc_train)
  satirlar.append(
      {
          "Model": ad,
          "Eğitim" : accuracy_score(yc_train,m.predict(Xc_train)),
          "Test": accuracy_score(yc_test,m.predict(Xc_test))
      }
  )

pd.DataFrame(satirlar).set_index("Model").round(3)

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay ,classification_report, roc_curve, roc_auc_score

model = siniflandiricilar["Logistic"]
tahmin = model.predict(Xc_test)
olasilik = model.predict_proba(Xc_test)[:,1]

fig ,axes = plt.subplots(1,2,figsize=(12,4))

cm = confusion_matrix(yc_test,tahmin)
ConfusionMatrixDisplay.from_predictions(yc_test,tahmin, display_labels =["habis","iyi huylu"], cmap="YlGn",ax=axes[0],colorbar=False)
axes[0].set_title("Karışıklık matrisi")
axes[0].grid(False)


for ad in ["Logistic","KNN","Karar ağacı","Rastgele orman"]:
  p=siniflandiricilar[ad].predict_proba(Xc_test)[:,1]
  fpr,tpr,_=roc_curve(yc_test,p)
  axes[1].plot(fpr,tpr,label=f"{ad} AUC:{roc_auc_score(yc_test,p):.3f}")
  axes[1].plot([0,1],[0,1],linestyle="--",color="gray")
  axes[1].set_xlabel("Yanlış pozitif oranı")
  axes[1].set_ylabel("Doğru pozitif oranı")
  axes[1].set_title("ROC eğrisi")
  axes[1].legend(fontsize=5)
  axes[1].grid(True)

plt.tight_layout()
plt.show()

from sklearn.model_selection import StratifiedKFold,cross_val_score

cv = StratifiedKFold(n_splits=5, shuffle =True, random_state=SEED)

satirlar =[]

for ad, m in siniflandiricilar.items():
  skorlar=cross_val_score(m,Xc_train,yc_train,cv=cv,scoring="accuracy")
  satirlar.append({"Model":ad,"Ortalama skor":skorlar.mean(),"Standart sapma":skorlar.std()})

cv_sonuc= pd.DataFrame(satirlar).set_index("Model").sort_values("Ortalama skor",ascending=False).round(3)
display(cv_sonuc)

from sklearn.model_selection import GridSearchCV

pipe = make_pipeline(StandardScaler(),KNeighborsClassifier())

param_grid = {
    "kneighborsclassifier__n_neighbors":[1,3,5,7,9,11,15,21],
    "kneighborsclassifier__weights":["uniform","distance"]
}

opt =GridSearchCV(pipe,param_grid,cv=cv,scoring="accuracy",n_jobs=-1)
opt.fit(Xc_train,yc_train)

print("best parametre:", opt.best_params_)
print(f"en iyi cv:{opt.best_score_:3f}")

scaler_yanlis= StandardScaler().fit(X_clf)
Xc_tr= scaler_yanlis.transform(Xc_train)
Xc_te= scaler_yanlis.transform(Xc_test)

scaler_dogru = StandardScaler().fit(Xc_train)
Xc_tr= scaler_dogru.transform(Xc_train)
Xc_te= scaler_dogru.transform(Xc_test)

print("yanlış yöntem " ,scaler_yanlis.mean_[:3].round(2))
print("doğru yöntem" ,scaler_dogru.mean_[:3].round(2))

from sklearn.preprocessing import PolynomialFeatures

rng = np.random.RandomState(SEED)
n = 40
x = np.sort(rng.uniform(0, 1, n))
y = np.sin(2 * np.pi * x) + rng.normal(0, 0.25, n)  # gerçek fonksiyon + gürültü

x_tr, x_te, y_tr, y_te = train_test_split(x.reshape(-1, 1), y, test_size=0.4, random_state=SEED)

xs = np.linspace(0, 1, 300).reshape(-1, 1)
dereceler = [1, 4, 15]
basliklar = ["Underfitting (derece 1)", "İyi uyum (derece 4)", "Overfitting (derece 15)"]

fig, axes = plt.subplots(1, 3, figsize=(15, 4), sharey=True)
for ax, d, b in zip(axes, dereceler, basliklar):
    model = make_pipeline(PolynomialFeatures(d), StandardScaler(), LinearRegression())
    model.fit(x_tr, y_tr)
    tr_hata = mean_squared_error(y_tr, model.predict(x_tr))
    te_hata = mean_squared_error(y_te, model.predict(x_te))
    ax.scatter(x_tr, y_tr, label="Eğitim", alpha=0.8)
    ax.scatter(x_te, y_te, label="Test", alpha=0.8, marker="s")
    ax.plot(xs, model.predict(xs), "r-", lw=2, label="Model")
    ax.plot(xs, np.sin(2 * np.pi * xs), "g--", lw=1, label="Gerçek f(x)")
    ax.set_ylim(-1.8, 1.8)
    ax.set_title(f"{b}\nEğitim MSE={tr_hata:.3f} | Test MSE={te_hata:.3f}", fontsize=10)
axes[0].legend(fontsize=8)
plt.tight_layout()
plt.show()

# Model karmaşıklığı arttıkça eğitim ve test hatası nasıl değişir?
derece_araligi = range(1, 16)
egitim_hatalari, test_hatalari = [], []

for d in derece_araligi:
    model = make_pipeline(PolynomialFeatures(d), StandardScaler(), LinearRegression())
    model.fit(x_tr, y_tr)
    egitim_hatalari.append(mean_squared_error(y_tr, model.predict(x_tr)))
    test_hatalari.append(mean_squared_error(y_te, model.predict(x_te)))

plt.figure(figsize=(7, 4))
plt.plot(derece_araligi, egitim_hatalari, "o-", label="Eğitim hatası")
plt.plot(derece_araligi, test_hatalari, "s-", label="Test hatası")
plt.yscale("log")
plt.xlabel("Model karmaşıklığı (polinom derecesi)")
plt.ylabel("MSE (log ölçek)")
plt.title("Bias–Variance dengesi")
plt.legend()
plt.tight_layout()
plt.show()

en_iyi = list(derece_araligi)[int(np.argmin(test_hatalari))]
print(f"Test hatasının en düşük olduğu derece: {en_iyi}")

"""## **K Means**

1.   Rastgele k merkez(centroid) seç
2.   Her örneği en yakın zamanda ata
3.   Merkezleri ,atanan örnekleri ortalaması
4.   Atamalarr değişmene kadar 2-3 tekrarla

"""

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, adjusted_rand_score

k_degerleri = range(2,9)
atalet, silhoutte= [],[]

for k in k_degerleri:
  km=KMeans(n_clusters=k, n_init=10,random_state=SEED).fit(Xc_tr)
  atalet.append(km.inertia_)
  silhoutte.append(silhouette_score(Xc_tr,km.labels_))


fig, axes =plt.subplots(1,2,figsize=(12,4))

axes[0].plot(k_degerleri,atalet,marker="o")
axes[0].set_title("Elbow")
axes[0].set_xlabel("K")
axes[0].set_ylabel("Atalet")

axes[1].plot(k_degerleri,silhoutte,marker="o")
axes[1].set_title("Silhoutte")
axes[1].set_xlabel("K")
axes[1].set_ylabel("Silhoutte")

plt.tight_layout()
plt.show()