# -*- coding: utf-8 -*-
"""24 Eylül.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uds0ImfTp0Qu_RhG1O5eIpI9DkE3wS8V
"""

import random
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

SEED=42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

X,y = load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=SEED)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model =keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(16, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(8, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(1,activation="sigmoid"),
])
model.summary()

model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.0001),
              loss=keras.losses.BinaryCrossentropy(),
              metrics=[keras.metrics.BinaryAccuracy(name="accuracy")])

from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

history = model.fit(X_train, y_train, validation_split=0.2, epochs=1, batch_size=4,verbose=2,callbacks=[early_stopping])

import torch
import torch.nn as nn
from torch.utils.data import TensorDataset,DataLoader,random_split

device =torch.device("cuda"if  torch.cuda.is_available() else "cpu")

X_train_tensor = torch.tensor(X_train,dtype=torch.float32)
y_train_tensor = torch.tensor(y_train,dtype=torch.float32).unsqueeze(1)
X_test_tensor = torch.tensor(X_test,dtype=torch.float32)
y_test_tensor = torch.tensor(y_test,dtype=torch.float32).unsqueeze(1)

full_ds = TensorDataset(X_train_tensor,y_train_tensor)
train_ds,val_ds = random_split(full_ds,[int(0.8*len(full_ds)),len(full_ds)-int(0.8*len(full_ds))])

train_loader = DataLoader(train_ds,batch_size=32,shuffle=True)
val_loader = DataLoader(val_ds,batch_size=32)

class ANN(nn.Module):
  def __init__ (self,n_features):
    super().__init__()
    self.net = nn.Sequential(
        nn.Linear(n_features,16),
        nn.ReLU(),
        nn.Dropout(0.2),
        nn.Linear(16,1),
        nn.Dropout(0.2),
    )

  def forward(self,x):
    return self.net(x)

model = ANN(X_train.shape[1]).to(device)
print(model)

criterion = nn.BCEWithLogitsLoss() # sigmoid + binary cross entropy
optimizer = torch.optim.Adam(model.parameters(),lr=0.001)

def accuracy(logits,targets):
  preds = (torch.sigmoid(logits)>0.5).float()
  return (preds==targets).float().mean()

EPOCHS =20

for epoch in range(1,EPOCHS+1):
  model.train()
  train_loss = 0
  train_acc = 0
  for batch_idx,(data,targets) in enumerate(train_loader):
    data,targets = data.to(device),targets.to(device)
    optimizer.zero_grad()
    logits = model(data)
    loss= criterion(logits,targets)
    loss.backward()
    optimizer.step()
    train_loss+=loss.item()*data.size(0)
    train_acc+=accuracy(logits,targets)

model.eval()
val_loss,val_correct = 0.0,0.0
with torch.no_grad():
  for data,targets in val_loader:
    data,targets = data.to(device),targets.to(device)
    logits = model(data)
    val_loss += criterion(logits,targets).item()*data.size(0)
    val_correct += accuracy(logits,targets)*data.size(0)
val_loss /= len(val_loader.dataset)
val_acc =val_correct/len(val_loader.dataset)
print(f"Epoch: {epoch}, Validation Loss: {val_loss:.4f}, Validation Accuracy: {val_acc:.4f}")

model.eval()
with torch.no_grad():
  test_logits = model(X_test_tensor.to(device))
  test_loss = criterion(test_logits,y_test_tensor.to(device))
  test_acc = accuracy(test_logits,y_test_tensor.to(device))
print(f"\n Test kaybı: {test_loss:.4f} | Test doğruluğu {test_acc:.4f}")

t= np.arange(2000)
series = np.sin(0.05*t)+0.5*np.sin(0.011*t)+np.random.normal(0,0.1,len(t))
series = series.astype("float32")

WİNDOW = 30

def make_windows(data,window):
  X,y =[] ,[]
  for i in range(len(data)-window):
    X.append(data[i:i+window])
    y.append(data[i+window])
  return np.array(X),np.array(y)

X,y = make_windows(series,WİNDOW)

split = int(0.8*len(X))
X_train,X_test = X[:split],X[split:]
y_train,y_test = y[:split],y[split:]
print("X_train",X_train.shape)
print("X_test",X_test.shape)
print("y_train",y_train.shape)
print("y_test",y_test.shape)

def build_model(cell ="lstm",units =32):
  rnn_layer = layers.LSTM(units) if cell == "lstm" else layers.GRU(units)
  model = keras.Sequential([
      layers.Input(shape=(X_train.shape[1],1)),
      rnn_layer,
      layers.Dense(1)
  ])
  model.compile(optimizer=keras.optimizers.Adam(1e-3),loss="mse",metrics =["mae"])
  return model

results = {}

for cell in ["lstm","gru"]:
  model = build_model(cell)
  model.summary()
  model.fit(
      X_train,
      y_train,
      epochs =20,
      batch_size =32,
      validation_split =0.1,
      verbose =2,
  )

mse,mae = model.evaluate(X_test,y_test)
print("MSE",mse)
print("MAE",mae)

VOCAB_SİZE = 10000
MAX_LEN = 200
EMBED_DIM = 128
LSTM =64

(X_train,y_train),(X_test,y_test) = keras.datasets.imdb.load_data(num_words=VOCAB_SİZE)
print(f"Eğitim:{len(X_train)} yorum | Test :{len(X_test)} yorum")

word_index = keras.datasets.imdb.get_word_index()
index_word = {index+3:word for word,index in word_index.items()}
index_word.update({0:"<PAD>",1:"<START>",2:"<OOV>"})
print("\n Örnek yorum:","".join(index_word.get(i,"?")for i in X_train[0][:40]),"....")
print("Etiket:","olumlu" if y_train[0]==1 else "olumsuz")

X_train = keras.utils.pad_sequences(X_train,maxlen=MAX_LEN,padding="post",truncating= "post")
X_test = keras.utils.pad_sequences(X_test,maxlen=MAX_LEN,padding="post",truncating= "post")

model = keras.Sequential([
    layers.Input(shape=(MAX_LEN,)),
    layers.Embedding(input_dim=VOCAB_SİZE,output_dim=EMBED_DIM, mask_zero=True),
    layers.LSTM(LSTM),
    layers.Dropout(0.2),
    layers.Dense(1,activation="sigmoid"),
    ])

early_stopping = keras.callbacks.EarlyStopping(monitor="val_loss",patience=2,restore_best_weights=True)
model.compile(optimizer=keras.optimizers.Adam(1e-3),loss="binary_crossentropy",metrics=["accuracy"])
model.summary()

import re
def encode_text(text):
    """Ham İngilizce metni modelin beklediği indeks dizisine çevirir."""
    words = re.sub(r"[^a-z0-9' ]", " ", text.lower()).split()
    ids = [1]  # <START>
    for w in words:
        idx = word_index.get(w)
        # Kelime sözlükte yoksa veya ilk VOCAB_SIZE içinde değilse -> <OOV>
        ids.append(idx + 3 if idx is not None and idx + 3 < VOCAB_SİZE else 2)
    return keras.utils.pad_sequences([ids], maxlen=MAX_LEN, padding="post", truncating="post")

examples = [
    "This movie was absolutely wonderful, the acting was brilliant and I loved every minute.",
    "What a waste of time. The plot was boring and the characters were terrible.",
    "It was okay, not great but not bad either.",
]

print("\n--- Yeni yorumlar üzerinde tahmin ---")
for text in examples:
    prob = float(model.predict(encode_text(text), verbose=0)[0, 0])
    label = "OLUMLU" if prob > 0.5 else "OLUMSUZ"
    print(f"[{label} | {prob:.3f}] {text}")

