# -*- coding: utf-8 -*-
"""lstm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HHsSSKDA2rwsIEJHo9moD8Ysy_hapA05
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import statsmodels.api as sm
from pandas import DataFrame , concat
from sklearn.metrics import mean_absolute_error , mean_squared_error
# %matplotlib inline
# %config InlineBackend.figure_format = 'retina'
from numpy import mean , concatenate
from math import sqrt
from pandas import read_csv
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,LSTM,Activation
from numpy import array , hstack
from tensorflow import keras
import tensorflow as tf
!pip install --upgrade yfinance
import yfinance as yf
import requests

import pandas as pd

import yfinance as yf
df = yf.Ticker("MSFT")

df = yf.Ticker("MSFT")
df = df.history(period='5y')
# Display the first few rows of the historical data
display(df.head())

# Initialize MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))

# Scale the combined data (features + target)
data_scaled = scaler.fit_transform(data_for_lstm)

# Assign to dfaset_stacked for subsequent steps
dfaset_stacked = data_scaled

print ("dfaset_stacked.shape" , dfaset_stacked.shape)

# Define the number of time steps for input (n_steps_in) and output (n_steps_out)
n_steps_in, n_steps_out = 60 , 30

# Create sequences using the pre-defined split_sequences function
X, y = split_sequences(dfaset_stacked, n_steps_in, n_steps_out)

print ("X.shape" , X.shape)
print ("y.shape" , y.shape)

# Define the split ratio for training and testing data
split_ratio = 0.8
train_size = int(len(X) * split_ratio)

# Split the data into training and testing sets
train_X , train_y = X[:train_size, :] , y[:train_size, :]
test_X , test_y = X[train_size:, :] , y[train_size:, :]

# Determine the number of features (columns in the input X)
n_features = train_X.shape[2]

print ("train_X.shape" , train_X.shape)
print ("train_y.shape" , train_y.shape)
print ("test_X.shape" , test_X.shape)
print ("test_y.shape" , test_y.shape)
print ("n_features" , n_features)

opt = keras.optimizers.Adam(learning_rate=0.01)

# Define the LSTM model architecture
model = Sequential()
# First LSTM layer: returns sequences for the next LSTM layer
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_steps_in, n_features)))
# Second LSTM layer: processes sequences from the first layer
model.add(LSTM(50, activation='relu'))
# Dense output layer: predicts n_steps_out values
model.add(Dense(n_steps_out))
model.add(Activation('linear')) # Linear activation for regression output

# Compile the model with Adam optimizer and Mean Squared Error loss
model.compile(optimizer=opt, loss='mse')







# Train the LSTM model
history = model.fit(train_X , train_y , epochs=1 , batch_size=1, verbose=1 ,validation_data=(test_X, test_y) ,shuffle=False)

