# -*- coding: utf-8 -*-
"""pandas_matplotlib_bilgi_testi.ipynb

Automatically generated by Colab.

# Pandas & Matplotlib Bilgi Testi

## Hazırlık**Soru 0:** `pandas`'ı `pd`, `numpy`'ı `np`, `matplotlib.pyplot`'u `plt` takma adıyla içe aktarın.
"""

# Kodunuzu buraya yazın

"""---## Bölüm 1 — Series**Soru 1.1:** Bir kırtasiyedeki ürünlerin stok adetlerini tutan bir Series oluşturun: index = `['Kalem','Defter','Silgi','Cetvel']`, değerler = `[300, 150, 80, 45]`.**Soru 1.2:** `'Silgi'` ürününün stok adedini index adıyla seçip yazdırın.**Soru 1.3:** Stoğu en az olan ürünü `.idxmin()` ile bulun.**Soru 1.4:** Tüm ürünlerin toplam stok adedini `.sum()` ile hesaplayın."""

# 1.1# 1.2# 1.3# 1.4

"""---## Bölüm 2 — DataFrame Oluşturma**Soru 2.1:** Bir spor salonundaki üyeleri temsil eden, `uye_adi`, `paket_turu` (örn. Aylık, Yıllık) ve `odenen_tutar` sütunlarından oluşan, en az 5 satırlık bir DataFrame oluşturun.**Soru 2.2:** `.shape` ile kaç üye ve kaç bilgi sütunu olduğunu kontrol edin.**Soru 2.3:** `.columns` ile sütun isimlerini listeleyin."""

# 2.1# 2.2# 2.3

"""---## Bölüm 3 — CSV/Excel Okuma (Kavramsal)Gerçek bir dosyanız olmasa da sözdizimini test edelim.**Soru 3.1:** `"satislar.csv"` adlı bir dosyayı okuyup `df_csv` değişkenine atayan kodu yazın (dosya olmadığı için hata verecektir, bu normaldir — sadece doğru sözdizimini yazın).**Soru 3.2:** `"rapor.xlsx"` adlı bir Excel dosyasını okuyup `df_excel` değişkenine atayan kodu yazın."""

# 3.1# 3.2

"""---## Bölüm 4 — Veriyi İncelemeAşağıdaki hücreyi çalıştırarak bir e-ticaret sipariş verisi oluşturun:"""

df = pd.DataFrame({    "siparis_no": [1001, 1002, 1003, 1004, 1005, 1006, 1007],    "kargo_suresi": [2, 5, 3, np.nan, 1, 4, 6],    "urun_adedi": [1, 3, 2, 5, 1, 2, 4],    "toplam_tutar": [150.0, 480.5, 220.0, 610.0, 90.0, 310.0, 720.0]})df

"""**Soru 4.1:** `.head(3)` ve `.tail(2)` ile ilk 3 ve son 2 siparişi görüntüleyin.**Soru 4.2:** `.info()` ile hangi sütunda eksik veri olduğunu tespit edin.**Soru 4.3:** `.describe()` ile kargo süresi, ürün adedi ve toplam tutarın istatistiklerini inceleyin."""

# 4.1# 4.2# 4.3

"""---## Bölüm 5 — Sütun ve Satır SeçmeYukarıdaki sipariş `df`'ini kullanarak:**Soru 5.1:** Sadece `siparis_no` ve `toplam_tutar` sütunlarını seçip yazdırın.**Soru 5.2:** `.loc[]` ile 0'dan 3'e kadar olan (0-3 dahil) satırları seçin.**Soru 5.3:** `.iloc[]` ile ilk 4 satırın son 2 sütununu seçin."""

# 5.1# 5.2# 5.3

"""---## Bölüm 6 — Filtreleme ve Yeni Sütun**Soru 6.1:** Toplam tutarı 300 TL'nin üzerinde olan siparişleri filtreleyin.**Soru 6.2:** Ürün adedi 2'den fazla VE toplam tutar 200 TL'den fazla olan siparişleri bulun (`&` kullanın).**Soru 6.3:** `birim_fiyat` adında yeni bir sütun ekleyin; değeri `toplam_tutar / urun_adedi` olsun.**Soru 6.4:** `apply` ve `lambda` kullanarak kargo süresi 3 günden fazlaysa "Yavaş", değilse "Hızlı" yazan bir `kargo_durumu` sütunu oluşturun."""

# 6.1# 6.2# 6.3# 6.4

"""---## Bölüm 7 — Sıralama**Soru 7.1:** Siparişleri `toplam_tutar` sütununa göre büyükten küçüğe sıralayın.**Soru 7.2:** Siparişleri önce `urun_adedi`, sonra `kargo_suresi` sütununa göre (ikisi de küçükten büyüğe) sıralayın (bir listede iki sütun verin)."""

# 7.1# 7.2

"""---## Bölüm 8 — Eksik Veri (NaN)**Soru 8.1:** `kargo_suresi` sütununda kaç eksik değer olduğunu bulun.**Soru 8.2:** Eksik kargo süresini sütunun **medyanı** ile doldurup `df_dolu` adlı yeni bir DataFrame oluşturun.**Soru 8.3:** Eksik değer içeren satırı silerek `df_temiz` adlı yeni bir DataFrame oluşturun ve satır sayısının değiştiğini `.shape` ile doğrulayın."""

# 8.1# 8.2# 8.3

"""---## Bölüm 9 — Merge (Tabloları Birleştirme)Aşağıdaki iki tabloyu kullanın:"""

musteriler = pd.DataFrame({    "musteri_id": [1, 2, 3, 4],    "ad": ["Baran", "Ceylin", "Emre", "Fulya"]})siparisler = pd.DataFrame({    "musteri_id": [1, 2, 5],    "urun": ["Kulaklık", "Şarj Kablosu", "Powerbank"],    "tutar": [450, 90, 320]})

"""**Soru 9.1:** `musteriler` ve `siparisler` tablolarını **inner join** ile birleştirin — kaç müşterinin siparişi eşleşiyor?**Soru 9.2:** Aynı tabloları **left join** ile birleştirin — hiç siparişi olmayan müşteri(ler) sonuçta ne görünüyor?**Soru 9.3:** Aynı tabloları **outer join** ile birleştirip, hem eşleşmeyen müşterileri hem eşleşmeyen siparişleri gözlemleyin."""

# 9.1# 9.2# 9.3

"""---## Bölüm 10 — Concat**Soru 10.1:** `hafta1 = pd.DataFrame({"gun":["Pzt","Sal"], "adet":[20,35]})` ve `hafta2 = pd.DataFrame({"gun":["Çar","Per"], "adet":[28,40]})` tablolarını `ignore_index=True` ile alt alta birleştirin.**Soru 10.2:** `gelir = pd.DataFrame({"toplam_gelir":[1000,1750]})` tablosunu, `hafta1` tablosuyla `axis=1` kullanarak yan yana birleştirin."""

# 10.1# 10.2

"""---## Bölüm 11 — GroupByAşağıdaki veriyi kullanın:"""

df_calisan = pd.DataFrame({    "sube": ["Kadıköy", "Beşiktaş", "Kadıköy", "Şişli", "Beşiktaş"],    "ad": ["Baran", "Ceylin", "Emre", "Fulya", "Gökhan"],    "satis": [12000, 18500, 9500, 21000, 16000]})

"""**Soru 11.1:** Şubeye göre **toplam** satışı bulun.**Soru 11.2:** Şubeye göre **ortalama** satışı bulun.**Soru 11.3:** `.agg(["sum","mean","count"])` kullanarak şube başına üç istatistiği aynı anda hesaplayın."""

# 11.1# 11.2# 11.3

"""---## Bölüm 12 — Pivot TableAşağıdaki veriyi kullanın:"""

df_satis = pd.DataFrame({    "sehir": ["Bursa", "Adana", "Antalya", "Bursa", "Adana"],    "kategori": ["Elektronik", "Giyim", "Elektronik", "Giyim", "Elektronik"],    "satis": [5000, 3200, 4100, 2800, 3900]})

"""**Soru 12.1:** `index="sehir"`, `columns="kategori"`, `values="satis"` ile bir pivot tablo oluşturun.**Soru 12.2:** Aynı pivot tabloyu `aggfunc="sum"` ve `fill_value=0` parametreleriyle oluşturup eksik hücrelerin nasıl doldurulduğunu gözlemleyin."""

# 12.1# 12.2

"""---## Bölüm 13 — Apply ile String İşlemleri**Soru 13.1:** `df_kullanici = pd.DataFrame({"kullanici_adi": ["baran23", "CEYLIN_K", "emre.y"]})` oluşturun.**Soru 13.2:** `apply(str.lower)` kullanarak tüm kullanıcı adlarını küçük harfe çeviren bir `kullanici_adi_kucuk` sütunu ekleyin.**Soru 13.3:** `apply` ve `lambda` ile kullanıcı adının kaç karakter olduğunu gösteren bir `karakter_sayisi` sütunu ekleyin."""

# 13.1# 13.2# 13.3

"""---## Bölüm 14 — Veri Tipi Dönüşümü (astype)**Soru 14.1:** `df_urun = pd.DataFrame({"urun_id":["10","11","12"], "agirlik_kg":["1.5","0.75","3.2"]})` oluşturun.**Soru 14.2:** `.info()` ile sütunların `object` (metin) tipinde olduğunu doğrulayın.**Soru 14.3:** `urun_id` sütununu `int`, `agirlik_kg` sütununu `float` tipine dönüştürüp tekrar `.info()` ile kontrol edin."""

# 14.1# 14.2# 14.3

"""---## Bölüm 15 — Matplotlib ile Grafik ÇizmeAşağıdaki hücreyi çalıştırarak bir yıllık çeyreklik gelir verisi oluşturun:"""

df_gelir = pd.DataFrame({    "ceyrek": ["Ç1", "Ç2", "Ç3", "Ç4"],    "gelir": [42000, 55000, 48000, 61000],    "gider": [30000, 38000, 33000, 40000]})

"""**Soru 15.1:** `gelir` değerlerini `kind="line"` ile, üzerinde nokta işaretleri (`marker="o"`) olacak şekilde çizgi grafikle çizin; başlık ve eksen etiketleri ekleyin.**Soru 15.2:** `gelir` değerlerini çeyreklere göre `kind="bar"` ile bar grafikle çizin (renk seçiminiz size ait).**Soru 15.3:** `gelir` sütununu çeyreklerin payını gösterecek şekilde `kind="pie"` ile pasta grafikle çizin (`autopct="%1.1f%%"` kullanın).**Soru 15.4:** `gelir` ve `gider` sütunlarını `kind="scatter"` ile scatter grafikte karşılaştırın (x ekseni gelir, y ekseni gider olsun) ve grafiğin ne anlattığını bir cümleyle yorumlayın."""

# 15.1# 15.2# 15.3# 15.4

"""---## Bonus — Kapsamlı UygulamaBir online kursun satış verisini simüle edin:1. `kurs_adi`, `kategori` (örn. Yazılım, Tasarım, Pazarlama) ve `satis_adedi` sütunlarından oluşan, en az 8 satırlık bir DataFrame oluşturun.2. Kategoriye göre toplam satış adedini `groupby` ile bulun.3. En çok satan 3 kursu `.sort_values()` ile bulun.4. Kategori bazında toplam satışı gösteren bir bar grafik çizin.5. `apply` ile satış adedi 50 üzeri olanlara "Popüler", altındakilere "Standart" yazan yeni bir sütun ekleyin."""

# Bonus uygulama